// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.1
//   protoc               v3.21.12
// source: admin.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "notification";

export interface SendGlobalNotificationRequest {
  title: string;
  body: string;
}

export interface SendUserNotification {
  userId: string;
  title: string;
  body: string;
}

export interface NotificationResponse {
  message: string;
  success: boolean;
}

export const NOTIFICATION_PACKAGE_NAME = "notification";

export interface notificationServiceClient {
  sendGlobalNotification(request: SendGlobalNotificationRequest, metadata?: Metadata): Observable<NotificationResponse>;

  sendUserNotification(request: SendUserNotification, metadata?: Metadata): Observable<NotificationResponse>;
}

export interface notificationServiceController {
  sendGlobalNotification(
    request: SendGlobalNotificationRequest,
    metadata?: Metadata,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;

  sendUserNotification(
    request: SendUserNotification,
    metadata?: Metadata,
  ): Promise<NotificationResponse> | Observable<NotificationResponse> | NotificationResponse;
}

export function notificationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["sendGlobalNotification", "sendUserNotification"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("notificationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("notificationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_SERVICE_NAME = "notificationService";
